// Code generated by Slice Machine. DO NOT EDIT.

import Header from './Header/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	header: Header,
	rich_text: RichText
};
