// Code generated by Slice Machine. DO NOT EDIT.

import Articles from './Articles/index.svelte';
import Header from './Header/index.svelte';
import QuickLinks from './QuickLinks/index.svelte';

export const components = {
	articles: Articles,
	header: Header,
	quick_links: QuickLinks
};
